INSERT INTO MY_NOTE (ID, TITLE, CONTENT) VALUES (1, 'Hello', 'World');
INSERT INTO MY_NOTE (ID, TITLE, CONTENT) VALUES (2, 'France', 'Paris');
INSERT INTO MY_NOTE (ID, TITLE, CONTENT) VALUES (3, 'Brazil', 'Brasilia');
INSERT INTO MY_NOTE (ID, TITLE, CONTENT) VALUES (4, 'Italy', 'Rome');
INSERT INTO MY_NOTE (ID, TITLE, CONTENT) VALUES (5, 'Canada', 'Ottawa');